# Generated by Django 2.2.9 on 2020-01-30 22:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('address', models.TextField()),
                ('profile_img', models.ImageField(upload_to='myresource/images/upload/profile_photo/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresource.Users')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField()),
                ('title', models.CharField(max_length=64)),
                ('details', ckeditor.fields.RichTextField()),
                ('imgs', models.ImageField(upload_to='myresource/images/upload/daily_pic/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresource.Users')),
            ],
        ),
    ]
