# Generated by Django 2.2.9 on 2020-02-06 15:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('address', models.TextField()),
                ('profile_img', models.ImageField(upload_to='myresource/upload/profile_photo/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresource.Users')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('event_special', models.CharField(max_length=16)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('event_color', models.CharField(max_length=16)),
                ('event_editable', models.CharField(default='true', max_length=16)),
                ('event_url', models.CharField(max_length=512)),
                ('event_details', ckeditor.fields.RichTextField()),
                ('event_imgs', models.ImageField(upload_to='myresource/upload/daily_pic/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresource.Users')),
            ],
        ),
    ]
