# Generated by Django 2.2.9 on 2020-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='123@123.com', max_length=254),
            preserve_default=False,
        ),
    ]
