# Generated by Django 2.2.9 on 2020-02-06 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
