# Generated by Django 2.2.9 on 2020-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0002_auto_20200206_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
