# Generated by Django 2.2.9 on 2020-02-03 23:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0002_auto_20200131_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='details',
            new_name='event_details',
        ),
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='imgs',
            new_name='event_imgs',
        ),
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='datatime',
            new_name='time_end',
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='event_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='event_editable',
            field=models.CharField(default=datetime.datetime(2020, 2, 3, 23, 7, 20, 615079), max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyroutine',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
