# Generated by Django 2.2.9 on 2020-02-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0003_auto_20200203_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroutine',
            name='event_url',
            field=models.CharField(default='www.baidu.com', max_length=512),
            preserve_default=False,
        ),
    ]
