# Generated by Django 2.2.9 on 2020-02-06 22:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0003_auto_20200206_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='event_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyroutine',
            name='event_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
