# Generated by Django 2.2.9 on 2020-02-04 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0004_dailyroutine_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroutine',
            name='event_special',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyroutine',
            name='event_editable',
            field=models.CharField(default='true', max_length=16),
        ),
    ]
