# Generated by Django 2.2.9 on 2020-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresource', '0005_auto_20200204_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='event_imgs',
            field=models.ImageField(upload_to='myresource/upload/daily_pic/'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='profile_img',
            field=models.ImageField(upload_to='myresource/upload/profile_photo/'),
        ),
    ]
